[package]
name = "neyuki"
version = "0.1.0"
edition = "2024"
description = "A small Lua-like scripting language implemented in Rust"
readme = "README.md"
license = "MIT"
license-file = "LICENSE"
repository = "https://github.com/neyuki-lang/neyuki"
homepage = "https://neyuki.cc/"

[dependencies]
num-bigint = "0.4"
num-integer = "0.1"
num-traits = "0.2"
rand = "0.8"
